import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/component";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ERP Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}</body>
    </html>
  );
}
